# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-XUL
version:      0.0401
version_from: lib/POE/XUL.pm
installdirs:  site
requires:
    Carp:                          0
    Digest::MD5:                   2.3
    HTTP::Date:                    1.4
    HTTP::Status:                  1
    JSON::XS:                      0.8
    MIME::Types:                   1.13
    POE:                           0.9500
    POE::Component::Server::HTTP:  0.09
    Scalar::Util:                  1.13
    Test::More:                    0.60
    Time::HiRes:                   1
    Unicode::String:               2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
