--- #YAML:1.0
name:                POE-XUL
version:             0.0200
abstract:            Server-side XUL for POE
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Carp:                          0
    Digest::MD5:                   2.3
    HTTP::Date:                    1.4
    HTTP::Status:                  1
    JSON::XS:                      0.8
    MIME::Types:                   0
    POE:                           0.9500
    POE::Component::Server::HTTP:  0.09
    Scalar::Util:                  1.13
    Test::More:                    0.60
    Time::HiRes:                   1
    Unicode::String:               2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Philip Gwyn <gwyn at cpan.org>
