--- #YAML:1.0
name:               POE-XUL
version:            0.0600
abstract:           Server-side XUL for POE
author:
    - Philip Gwyn <gwyn at cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Digest::MD5:          2.3
    HTML::Entities:       1.35
    HTTP::Date:           1.4
    HTTP::Status:         1
    I18N::AcceptLanguage:  1.04
    JSON::XS:             0.8
    MIME::Types:          1.13
    POE:                  0.9500
    POE::Component::Server::HTTP:  0.09
    Scalar::Util:         1.13
    Test::More:           0.60
    Time::HiRes:          1
    Unicode::String:      2
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
